BOT_TOKEN = ''
API_KEY = ''
MANIFEST_URL = 'https://minter.theopenpass.io/bot/0/tonconnect-manifest.json'
NFT_CONTRACT = 'EQBOWos8X1kWmzu1ds7FNYUxyZJckY8au99sKV8vMpOinHqs'
GROUP_LINK = ''
CHAT_ID = ''
